import Foundation

func check(_ value: @autoclosure () -> Bool, _ message: String) { if !value() { fatalError(message) } }
let screen = ANSIScreen()
screen.resize(10, 3)
screen.feed(Data("hello\rOK\u{1b}[K".utf8))
check(screen.grid[0].joined().hasPrefix("OK   "), "CR + erase line must clear old shell text")
screen.reset()
let unicode = Array("你好".utf8)
screen.feed(Data(unicode.prefix(2)))
check(screen.grid[0][0] == " ", "Incomplete UTF8 must wait for next packet")
screen.feed(Data(unicode.dropFirst(2)))
check(screen.grid[0][0] == "你" && screen.grid[0][2] == "好", "Split UTF8 and CJK cells")
screen.feed(Data("\u{1b}[?1049hother\u{1b}[?1049l".utf8))
check(screen.grid[0][0] == "你", "Alternate screen must restore primary content")
screen.resize(80, 24); screen.feed(Data("\u{1b}[24;80H\u{1b}7".utf8)); screen.resize(10, 3); screen.feed(Data("\u{1b}8X".utf8))
check(screen.y < 3 && screen.x < 10, "Saved cursor must stay in bounds after resize")
screen.reset(); screen.feed(Data("one\r\ntwo\r\nthree\r\nfour".utf8))
check(screen.history.count == 1 && screen.history[0].hasPrefix("one"), "Shell scrollback")
let actual = try Pocket.bridgeAddress("https://friendly-space.github.dev")
check(actual == "https://friendly-space-8765.app.github.dev", "Codespace URL conversion")
for bad in ["http://friendly-space.github.dev", "https://friendly-space.github.dev.evil.test", "https://user:password@friendly-space.github.dev", "https://friendly-space.github.dev?token=secret", "https://app.github.dev", "https://friendly-space.github.dev:443", "https://friendly-space.github.dev/arbitrary"] {
    do { _ = try Pocket.bridgeAddress(bad); fatalError("Accepted an unsafe workspace URL") } catch { }
}
print("PASS: native ANSI streaming, Unicode, screen restore, resize bounds, scrollback and credential URL boundaries")
// Keyboard resize must preserve output around the shell cursor.
let resized = ANSIScreen()
resized.resize(20, 6)
resized.feed(Data("one\r\ntwo\r\nthree\r\nfour\r\nfive\r\nsix".utf8))
resized.resize(20, 3)
check(resized.history.count == 3, "Shrinking rows must retain earlier lines in scrollback")
check(resized.grid[2].joined().hasPrefix("six") && resized.y == 2, "Keyboard resize must retain latest line and cursor")
check(resized.text.contains("one") && resized.text.contains("six"), "Resize must not erase output")
resized.resize(20, 6)
check(resized.grid[2].joined().hasPrefix("six"), "Growing terminal must preserve prompt")
let pasted = ANSIScreen()
check(String(data: pasted.pasteData("a\r\nb"), encoding: .utf8) == "a\rb", "Normalize clipboard CRLF once")
pasted.feed(Data("\u{1b}[?2004h".utf8))
check(String(data: pasted.pasteData("a\r\nb"), encoding: .utf8) == "\u{1b}[200~a\nb\u{1b}[201~", "Bracketed paste protects multiline shell input")
pasted.feed(Data("\u{1b}[?2004l".utf8))
check(!pasted.bracketedPaste, "Shell may disable bracketed paste")
pasted.feed(Data("\u{1b}cOK".utf8))
check(pasted.grid[0].joined().hasPrefix("OK"), "Reset inside packet must not break decoding")
pasted.reset(); pasted.feed(Data("你a".utf8))
check(pasted.cursorOffset == 2, "Cursor offset must count UTF16 characters rather than screen cells")
print("PASS: keyboard resize retention, paste protocol, reset streaming and cursor offset")

let cleanSession = ANSIScreen()
cleanSession.feed(Data([0xe4, 0xbd]))
cleanSession.reset()
cleanSession.feed(Data("OK".utf8))
check(cleanSession.grid[0].joined().hasPrefix("OK"), "New session must discard partial UTF8 from the old shell")
cleanSession.feed(Data("\u{1b}[?25l".utf8))
check(!cleanSession.cursorVisible, "Respect remote hidden cursor mode")
cleanSession.feed(Data("\u{1b}[?25h".utf8))
check(cleanSession.cursorVisible, "Restore remote cursor visibility")
cleanSession.feed(Data("\u{1b}[9223372036854775807C\u{1b}[9223372036854775807X".utf8))
check(cleanSession.x == cleanSession.cols - 1, "Large CSI parameters must clamp without integer overflow")
check(ANSIScreen.cells("你a") == ["你", "", "a"], "Scrollback must retain double-width columns")
check(ANSIScreen.cells("e\u{301}x").count == 2, "Combining accents must occupy one terminal cell")
print("PASS: isolated sessions, cursor visibility, hostile CSI bounds and drawing cell widths")
